name: solgasdelivery
description: Proyecto Flutter para delivery con Firebase
publish_to: "none" # No lo publiques en pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.5

  # UI y utilidades
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Splash screen (versión compatible con flutter_test)
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/
