name: solgasdelivery
description: Aplicación de pedidos y administración para Solgas Delivery
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2

  # UI
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6

  # Estado y utilidades
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Configuración de íconos
flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/images/icon.png"

# Configuración de splash
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  android: true
  ios: true
  web: true
