// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrXWIgRu1oSK9c9P7yHOIdrIWgdn_Dyow',
    appId: '1:745838882023:web:99a53b504e8c1e9268c642',
    messagingSenderId: '745838882023',
    projectId: 'solgasdelivery-69729',
    authDomain: 'solgasdelivery-69729.firebaseapp.com',
    storageBucket: 'solgasdelivery-69729.firebasestorage.app',
    measurementId: 'G-XDQ3B2JEN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCHKtRDGxv7JA5FsjkwUC9rLFlFYtSWsU',
    appId: '1:745838882023:android:388643c95b255c6668c642',
    messagingSenderId: '745838882023',
    projectId: 'solgasdelivery-69729',
    storageBucket: 'solgasdelivery-69729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2KKAa9DkYTIrXluUGRRNu7DUL63UzVlc',
    appId: '1:745838882023:ios:a17d4b68b1f18bfb68c642',
    messagingSenderId: '745838882023',
    projectId: 'solgasdelivery-69729',
    storageBucket: 'solgasdelivery-69729.firebasestorage.app',
    iosBundleId: 'com.example.gasDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2KKAa9DkYTIrXluUGRRNu7DUL63UzVlc',
    appId: '1:745838882023:ios:a17d4b68b1f18bfb68c642',
    messagingSenderId: '745838882023',
    projectId: 'solgasdelivery-69729',
    storageBucket: 'solgasdelivery-69729.firebasestorage.app',
    iosBundleId: 'com.example.gasDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrXWIgRu1oSK9c9P7yHOIdrIWgdn_Dyow',
    appId: '1:745838882023:web:ff46d62a49ed721668c642',
    messagingSenderId: '745838882023',
    projectId: 'solgasdelivery-69729',
    authDomain: 'solgasdelivery-69729.firebaseapp.com',
    storageBucket: 'solgasdelivery-69729.firebasestorage.app',
    measurementId: 'G-VFZJGVKRL5',
  );
}
